<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HMECL002384" ignored="0" name="Test" tests="11" failures="2" timestamp="2020-03-24T17:57:26 IST" time="26.133" errors="0">
  <testcase name="testcase1" time="11.533" classname="demo.cmd_test_10"/>
  <testcase name="testcase2" time="0.186" classname="demo.cmd_test_10"/>
  <testcase name="testcase3" time="0.114" classname="demo.cmd_test_10"/>
  <testcase name="testcase4" time="1.102" classname="demo.cmd_test_10"/>
  <testcase name="testcase5" time="3.073" classname="demo.cmd_test_10">
    <failure type="java.lang.AssertionError" message="expected [https://online.actitime.com/tcs/login.do] but found [expected]">
      <![CDATA[java.lang.AssertionError: expected [https://online.actitime.com/tcs/login.do] but found [expected]
at demo.cmd_test_10.testcase5(cmd_test_10.java:40)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testcase5 -->
  <testcase name="testcase6" time="0.0" classname="demo.cmd_test_10">
    <skipped/>
  </testcase> <!-- testcase6 -->
  <testcase name="testcase7" time="7.664" classname="demo.cmd_test_10"/>
  <testcase name="testcase8" time="0.122" classname="demo.cmd_test_10"/>
  <testcase name="testcase9" time="0.14" classname="demo.cmd_test_10">
    <failure type="java.lang.AssertionError" message="expected [5678] but found [2345]">
      <![CDATA[java.lang.AssertionError: expected [5678] but found [2345]
at demo.cmd_test_10.testcase9(cmd_test_10.java:61)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testcase9 -->
  <testcase name="testcase10" time="0.0" classname="demo.cmd_test_10">
    <skipped/>
  </testcase> <!-- testcase10 -->
  <testcase name="testcase11" time="2.131" classname="demo.cmd_test_10"/>
</testsuite> <!-- Test -->
